// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBzIm1R3OsFa-qbWsl6JHRYeZaHQGwsTs',
    appId: '1:238117498783:web:47f45ab3bf26250a6297aa',
    messagingSenderId: '238117498783',
    projectId: 'moodscope-d8db9',
    authDomain: 'moodscope-d8db9.firebaseapp.com',
    storageBucket: 'moodscope-d8db9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhAduGa9xsHSQDJV6P-e_eHiJcDyJ1XBs',
    appId: '1:238117498783:android:f5661bb3b73c469a6297aa',
    messagingSenderId: '238117498783',
    projectId: 'moodscope-d8db9',
    storageBucket: 'moodscope-d8db9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFB7yIQnHjqPAbTBkKxsEiHX8-XfPwc_U',
    appId: '1:238117498783:ios:26049d13de3429b86297aa',
    messagingSenderId: '238117498783',
    projectId: 'moodscope-d8db9',
    storageBucket: 'moodscope-d8db9.firebasestorage.app',
    iosClientId: '238117498783-s1qlfjdeek5ismsjpmq2mtso54irnn3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodscapeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFB7yIQnHjqPAbTBkKxsEiHX8-XfPwc_U',
    appId: '1:238117498783:ios:26049d13de3429b86297aa',
    messagingSenderId: '238117498783',
    projectId: 'moodscope-d8db9',
    storageBucket: 'moodscope-d8db9.firebasestorage.app',
    iosClientId: '238117498783-s1qlfjdeek5ismsjpmq2mtso54irnn3e.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodscapeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBzIm1R3OsFa-qbWsl6JHRYeZaHQGwsTs',
    appId: '1:238117498783:web:be6a8ecec57f975d6297aa',
    messagingSenderId: '238117498783',
    projectId: 'moodscope-d8db9',
    authDomain: 'moodscope-d8db9.firebaseapp.com',
    storageBucket: 'moodscope-d8db9.firebasestorage.app',
  );

}